name: Build MDT Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build EXE with electron-builder
        run: npm run dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: MDT-Installer-Setup
          path: dist/*.exe
